/*
 * WeatherData - A data model class for storing weather information.
 *
 * This class holds essential weather data, such as temperature, humidity, wind speed,
 * and general weather condition. It provides getter and setter methods to access
 * and modify each data field, making it a basic model in a weather app's architecture.
 *
 * Fields:
 * - temperature (double): Stores the temperature in degrees.
 * - humidity (int): Stores the humidity percentage.
 * - windSpeed (double): Stores the wind speed, typically in meters per second.
 * - condition (String): Describes the weather condition (e.g., sunny, cloudy).
 *
 * Usage:
 * The WeatherData class can be used to encapsulate weather information fetched
 * from an API or generated by the application, facilitating data handling and display.
 */

package main.java.com.henry.weatherapp.model;

public class WeatherData {
    private double temperature;
    private int humidity;
    private double windSpeed;
    private String condition;

    // Getters and Setters
    public double getTemperature() { return temperature; }
    public void setTemperature(double temperature) { this.temperature = temperature; }

    public int getHumidity() { return humidity; }
    public void setHumidity(int humidity) { this.humidity = humidity; }

    public double getWindSpeed() { return windSpeed; }
    public void setWindSpeed(double windSpeed) { this.windSpeed = windSpeed; }

    public String getCondition() { return condition; }
    public void setCondition(String condition) { this.condition = condition; }
}
